USE [Westcon]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- exec [Starsoft].[Reports_EstoqueServico] '20170201','20170218'

ALTER PROCEDURE [Starsoft].[Reports_EstoqueServico]
	@PLD_INITIAL DATE, -- Data de inicio da pesquisa
	@PLD_FINAL DATE -- Data final da pesquisa

AS
BEGIN


    declare @initial_date as date
	declare @final_date as date

	set @initial_date = @PLD_INITIAL
	set @final_date = @PLD_FINAL

	SET NOCOUNT ON;

	
	SELECT * 
	INTO #TMP_RAZAO
	FROM (
		-- Armazeno os lançamentos Contábeis na Conta de Estoque 1106050001
		SELECT * 
		FROM [Westcon].[Starsoft].[fnFinancialPostingsPerAccountPerPeriodBR](@initial_date,@final_date,'1106050001')
		)TMP
	ORDER BY OPERACAO, NUMERO_OPERACAO, VALORLANCAMENTO

	--================================================TRATANDO DAS NOTAS DE ENTRADA===============================================================
	SELECT DISTINCT
	E10.UKEY,
	E10_001_C AS NOTA, 
	E10_003_D AS EMISSAO,
	CAST(E04_001_B AS MONEY) AS VALORNOTA,
	E10.E10_032_N AS CANCELADA,
	CAST('COMPRA' AS CHAR(254)) AS OBS,
	CAST(CIA.CIA_001_C AS CHAR(254)) AS EMPRESA
	INTO #TMP_NFE
	FROM STARWESTCON.DBO.E10 (NOLOCK)
	INNER JOIN STARWESTCON.DBO.E04 (NOLOCK) ON E04.E04_UKEYP = E10.UKEY AND E04.ARRAY_241 = 3
	INNER JOIN STARWESTCON.DBO.E11 (NOLOCK) ON E11.E10_UKEY = E10.UKEY
	INNER JOIN STARWESTCON.DBO.D07 (NOLOCK) ON E11.D07_UKEY0 = D07.UKEY
	INNER JOIN STARWESTCON.DBO.CIA (NOLOCK) ON E10.CIA_UKEY = CIA.UKEY
	WHERE E10_002_N = 1 AND 
	(D07_001_C LIKE '0602%' OR D07_001_C LIKE '0603%') AND 
	E10_003_D BETWEEN @initial_date AND @final_date

	SELECT
	OPERACAO,
	cast(DOCUMENTO as char(20)) as DOCUMENTO,
	VALOR_DOCUMENTO,
	EMISSAO AS EMISSAO,
	LANCAMENTO,
	VALOR_RAZAO,
	HISTORICO,
	CAST(CASE WHEN CANCELADA = 1 AND VALOR_RAZAO > 0 THEN 'CANCELADO MAS TEM LANCAMENTO NA CONTABILIDADE' 
								WHEN VALOR_DOCUMENTO = VALOR_RAZAO THEN 'SEM ERRO'
						ELSE  
								'DIFERENCA ENTRE ESTOQUE E CONTABILIDADE'
						END 
					AS CHAR(254)) AS MOTIVO,
	OBSERVACAO,
	EMPRESA,
	DOCUMENTO_UKEY
	INTO #TMP_RESULTADO
	FROM ( SELECT
		'NFE    ' AS OPERACAO,
		TMP_NFE.NOTA AS DOCUMENTO,
		TMP_NFE.VALORNOTA AS VALOR_DOCUMENTO,
		TMP_NFE.EMISSAO,
		TMP_RAZAO.LANCAMENTO,
		--TMP_RAZAO.VALORLANCAMENTO AS VALOR_RAZAO,
		CAST((SELECT SUM(ISNULL(#TMP_RAZAO.VALORLANCAMENTO,0)) FROM #TMP_RAZAO WHERE B06_UKEYP = TMP_NFE.UKEY) AS MONEY) AS VALOR_RAZAO,
		CAST(ISNULL(TMP_RAZAO.HISTORICO,'') AS VARCHAR(254)) AS HISTORICO,
		TMP_NFE.CANCELADA AS CANCELADA,
		CAST(TMP_NFE.OBS AS VARCHAR(254)) AS OBSERVACAO,
		TMP_NFE.EMPRESA AS EMPRESA,
		TMP_NFE.UKEY AS DOCUMENTO_UKEY
		FROM #TMP_NFE AS TMP_NFE
		JOIN #TMP_RAZAO AS TMP_RAZAO ON TMP_RAZAO.B06_UKEYP = TMP_NFE.UKEY 
	)TMP

	--DELETO AS NOTAS QUE FORAM TRATADAS
	DELETE #TMP_NFE WHERE UKEY IN (SELECT DOCUMENTO_UKEY FROM #TMP_RESULTADO)

	--DELETO OS LANÇAMENTOS QUE JÁ FORAM TRATADOS
	DELETE #TMP_RAZAO WHERE LANCAMENTO IN (SELECT LANCAMENTO FROM #TMP_RESULTADO)

	-- ARMAZENO AS DEMAIS NOTAS NO CURSOR DE RESULTADO
	INSERT INTO #TMP_RESULTADO 
	-- NF SEM TRATAMENTO
	SELECT 
			'NFE    ' AS OPERACAO,
			TMP_NFE.NOTA AS DOCUMENTO,
			TMP_NFE.VALORNOTA AS VALOR_DOCUMENTO,
			TMP_NFE.EMISSAO AS EMISSAO,
			'' AS LANCAMENTO,
			0 AS VALOR_RAZAO,
			'' AS HISTORICO,
			'NAO TEM LANCAMENTO NA CONTABILIDADE' AS MOTIVO,
			RTRIM(TMP_NFE.OBS) +  CASE WHEN TMP_NFE.CANCELADA = 1 THEN '-CANCELADA' ELSE '' END  AS OBSERVACAO,
			TMP_NFE.EMPRESA AS EMPRESA,
			TMP_NFE.UKEY AS DOCUMENTO_UKEY
	FROM #TMP_NFE AS TMP_NFE
	
	DROP TABLE #TMP_NFE
	--================================================FINALIZADO O TRATAMENTO DAS NOTAS DE ENTRADA===============================================================

	--================================================TRATANDO DAS DEVOLUÇÕES DE NOTAS DE ENTRADA===============================================================
	SELECT DISTINCT
	E10.UKEY,
	E10_001_C AS NOTA, 
	E10_003_D AS EMISSAO,
	CAST(E04_001_B AS MONEY) AS VALORNOTA,
	E10.E10_032_N AS CANCELADA,
	CAST('DEVOLUÇÃO DE COMPRA' AS CHAR(254)) AS OBS,
	CAST(CIA.CIA_001_C AS CHAR(254)) AS EMPRESA
	INTO #TMP_NFEDEV
	FROM STARWESTCON.DBO.E10 (NOLOCK)
	INNER JOIN STARWESTCON.DBO.E04 (NOLOCK) ON E04.E04_UKEYP = E10.UKEY AND E04.ARRAY_241 = 3
	INNER JOIN STARWESTCON.DBO.E11 (NOLOCK) ON E11.E10_UKEY = E10.UKEY
	INNER JOIN STARWESTCON.DBO.D07 (NOLOCK) ON E11.D07_UKEY0 = D07.UKEY
	INNER JOIN STARWESTCON.DBO.CIA (NOLOCK) ON E10.CIA_UKEY = CIA.UKEY
	WHERE E10_002_N = 2 AND 
	(D07_001_C LIKE '0602%' OR D07_001_C LIKE '0603%') AND 
	E10_003_D BETWEEN @initial_date AND @final_date

	INSERT INTO #TMP_RESULTADO
		SELECT
		OPERACAO,
		DOCUMENTO,
		VALOR_DOCUMENTO,
		EMISSAO AS EMISSAO,
		LANCAMENTO,
		VALOR_RAZAO,
		HISTORICO,
		CAST(CASE WHEN CANCELADA = 1 AND VALOR_RAZAO > 0 THEN 'CANCELADO MAS TEM LANCAMENTO NA CONTABILIDADE' 
									WHEN VALOR_DOCUMENTO = VALOR_RAZAO THEN 'SEM ERRO'
							ELSE  
									'DIFERENCA ENTRE ESTOQUE E CONTABILIDADE'
							END 
						AS CHAR(254)) AS MOTIVO,
		OBSERVACAO,
		EMPRESA,
		DOCUMENTO_UKEY
	
		FROM ( SELECT
			'DEV NFE' AS OPERACAO,
			TMP_NFEDEV.NOTA AS DOCUMENTO,
			TMP_NFEDEV.VALORNOTA AS VALOR_DOCUMENTO,
			TMP_NFEDEV.EMISSAO,
			TMP_RAZAO.LANCAMENTO,
			--TMP_RAZAO.VALORLANCAMENTO AS VALOR_RAZAO,
			CAST((SELECT SUM(ISNULL(#TMP_RAZAO.VALORLANCAMENTO,0)) FROM #TMP_RAZAO WHERE B06_UKEYP = TMP_NFEDEV.UKEY) AS MONEY) AS VALOR_RAZAO,
			CAST(ISNULL(TMP_RAZAO.HISTORICO,'') AS VARCHAR(254)) AS HISTORICO,
			TMP_NFEDEV.CANCELADA AS CANCELADA,
			CAST(TMP_NFEDEV.OBS AS VARCHAR(254)) AS OBSERVACAO,
			TMP_NFEDEV.EMPRESA AS EMPRESA,
			TMP_NFEDEV.UKEY AS DOCUMENTO_UKEY
			FROM #TMP_NFEDEV AS TMP_NFEDEV
			JOIN #TMP_RAZAO AS TMP_RAZAO ON TMP_RAZAO.B06_UKEYP = TMP_NFEDEV.UKEY 
		)TMP

	--DELETO AS NOTAS QUE FORAM TRATADAS
	DELETE #TMP_NFEDEV WHERE UKEY IN (SELECT DOCUMENTO_UKEY FROM #TMP_RESULTADO)

	--DELETO OS LANÇAMENTOS QUE JÁ FORAM TRATADOS
	DELETE #TMP_RAZAO WHERE LANCAMENTO IN (SELECT LANCAMENTO FROM #TMP_RESULTADO)

	-- ARMAZENO AS DEMAIS NOTAS NO CURSOR DE RESULTADO
	INSERT INTO #TMP_RESULTADO 
	SELECT 
			'DEV NFE' AS OPERACAO,
			TMP_NFEDEV.NOTA AS DOCUMENTO,
			TMP_NFEDEV.VALORNOTA AS VALOR_DOCUMENTO,
			TMP_NFEDEV.EMISSAO AS EMISSAO,
			'' AS LANCAMENTO,
			0 AS VALOR_RAZAO,
			'' AS HISTORICO,
			CAST('NAO TEM LANCAMENTO NA CONTABILIDADE' AS CHAR(254)) AS MOTIVO,
			RTRIM(TMP_NFEDEV.OBS) +  CASE WHEN TMP_NFEDEV.CANCELADA = 1 THEN 'CANCELADA' ELSE '' END  AS OBSERVACAO,
			TMP_NFEDEV.EMPRESA AS EMPRESA,
			TMP_NFEDEV.UKEY AS DOCUMENTO_UKEY
	FROM #TMP_NFEDEV AS TMP_NFEDEV
	
	DROP TABLE #TMP_NFEDEV
	--================================================FINALIZADO O TRATAMENTO DAS DEVOLUÇÕES DE  NOTAS DE ENTRADA===============================================================

	--================================================TRATANDO DAS NOTAS DE SAÍDA===============================================================
	SELECT DISTINCT
	J10.UKEY,
	J10_001_C AS NOTA, 
	J10_003_D AS EMISSAO,
	CAST(J06_001_B AS MONEY) AS VALORNOTA,
	J10.J10_032_N AS CANCELADA,
	CAST('VENDA' AS CHAR(254)) AS OBS,
	CAST(CIA.CIA_001_C AS CHAR(254)) AS EMPRESA
	INTO #TMP_NFS
	FROM STARWESTCON.DBO.J10 (NOLOCK)
	INNER JOIN STARWESTCON.DBO.J06 (NOLOCK) ON J06.J06_UKEYP = J10.UKEY AND J06.ARRAY_241 = 3
	INNER JOIN STARWESTCON.DBO.J11 (NOLOCK) ON J11.J10_UKEY = J10.UKEY
	INNER JOIN STARWESTCON.DBO.D07 (NOLOCK) ON J11.D07_UKEY = D07.UKEY
	INNER JOIN STARWESTCON.DBO.CIA (NOLOCK) ON J10.CIA_UKEY = CIA.UKEY
	WHERE J10_002_N = 1 AND 
	(D07_001_C LIKE '0602%' OR D07_001_C LIKE '0603%') AND 
	J10_003_D BETWEEN @initial_date AND @final_date
	
	INSERT INTO #TMP_RESULTADO
		SELECT
		OPERACAO,
		DOCUMENTO,
		VALOR_DOCUMENTO,
		EMISSAO AS EMISSAO,
		LANCAMENTO,
		VALOR_RAZAO,
		HISTORICO,
		CAST(CASE WHEN CANCELADA = 1 AND VALOR_RAZAO > 0 THEN 'CANCELADO MAS TEM LANCAMENTO NA CONTABILIDADE' 
									WHEN VALOR_DOCUMENTO = VALOR_RAZAO THEN 'SEM ERRO'
							ELSE  
									'DIFERENCA ENTRE ESTOQUE E CONTABILIDADE'
							END 
						AS CHAR(254)) AS MOTIVO,
		OBSERVACAO,
		EMPRESA,
		DOCUMENTO_UKEY
	
		FROM ( SELECT
			'NFS' AS OPERACAO,
			TMP_NFS.NOTA AS DOCUMENTO,
			TMP_NFS.VALORNOTA AS VALOR_DOCUMENTO,
			TMP_NFS.EMISSAO,
			TMP_RAZAO.LANCAMENTO,
			--TMP_RAZAO.VALORLANCAMENTO AS VALOR_RAZAO,
			CAST((SELECT SUM(ISNULL(#TMP_RAZAO.VALORLANCAMENTO,0)) FROM #TMP_RAZAO WHERE B06_UKEYP = TMP_NFS.UKEY) AS MONEY) AS VALOR_RAZAO,
			CAST(ISNULL(TMP_RAZAO.HISTORICO,'') AS VARCHAR(254)) AS HISTORICO,
			TMP_NFS.CANCELADA AS CANCELADA,
			CAST(TMP_NFS.OBS AS VARCHAR(254)) AS OBSERVACAO,
			TMP_NFS.EMPRESA AS EMPRESA,
			TMP_NFS.UKEY AS DOCUMENTO_UKEY
			FROM #TMP_NFS AS TMP_NFS
			JOIN #TMP_RAZAO AS TMP_RAZAO ON TMP_RAZAO.B06_UKEYP = TMP_NFS.UKEY 
		)TMP

	--DELETO AS NOTAS QUE FORAM TRATADAS
	DELETE #TMP_NFS WHERE UKEY IN (SELECT DOCUMENTO_UKEY FROM #TMP_RESULTADO)

	--DELETO OS LANÇAMENTOS QUE JÁ FORAM TRATADOS
	DELETE #TMP_RAZAO WHERE LANCAMENTO IN (SELECT LANCAMENTO FROM #TMP_RESULTADO)

	-- ARMAZENO AS DEMAIS NOTAS NO CURSOR DE RESULTADO
	INSERT INTO #TMP_RESULTADO 
	-- NF SEM TRATAMENTO
	SELECT 
			'NFS' AS OPERACAO,
			TMP_NFS.NOTA AS DOCUMENTO,
			TMP_NFS.VALORNOTA AS VALOR_DOCUMENTO,
			TMP_NFS.EMISSAO AS EMISSAO,
			'' AS LANCAMENTO,
			0 AS VALOR_RAZAO,
			'' AS HISTORICO,
			'NAO TEM LANCAMENTO NA CONTABILIDADE' AS MOTIVO,
			RTRIM(TMP_NFS.OBS) +  CASE WHEN TMP_NFS.CANCELADA = 1 THEN '-CANCELADA' ELSE '' END  AS OBSERVACAO,
			TMP_NFS.EMPRESA AS EMPRESA,
			TMP_NFS.UKEY AS DOCUMENTO_UKEY
	FROM #TMP_NFS AS TMP_NFS
	
	DROP TABLE #TMP_NFS
	--================================================FINALIZADO O TRATAMENTO DAS NOTAS DE SAÍDA===============================================================

	--================================================TRATANDO DAS DEVOLUÇÕES DE NOTAS DE SAÍDA===============================================================
	SELECT DISTINCT
	J10.UKEY,
	J10_001_C AS NOTA, 
	J10_003_D AS EMISSAO,
	CAST(J06_001_B AS MONEY) AS VALORNOTA,
	J10.J10_032_N AS CANCELADA,
	CAST('DEVOLUÇÃO VENDA' AS CHAR(254)) AS OBS,
	CAST(CIA.CIA_001_C AS CHAR(254)) AS EMPRESA
	INTO #TMP_NFSDEV
	FROM STARWESTCON.DBO.J10 (NOLOCK)
	INNER JOIN STARWESTCON.DBO.J06 (NOLOCK) ON J06.J06_UKEYP = J10.UKEY AND J06.ARRAY_241 = 3
	INNER JOIN STARWESTCON.DBO.J11 (NOLOCK) ON J11.J10_UKEY = J10.UKEY
	INNER JOIN STARWESTCON.DBO.D07 (NOLOCK) ON J11.D07_UKEY0 = D07.UKEY
	INNER JOIN STARWESTCON.DBO.CIA (NOLOCK) ON J10.CIA_UKEY = CIA.UKEY
	WHERE J10_002_N = 2 AND 
	(D07_001_C LIKE '0602%' OR D07_001_C LIKE '0603%') AND 
	J10_003_D BETWEEN @initial_date AND @final_date
	
	INSERT INTO #TMP_RESULTADO
		SELECT
		OPERACAO,
		DOCUMENTO,
		VALOR_DOCUMENTO,
		EMISSAO AS EMISSAO,
		LANCAMENTO,
		VALOR_RAZAO,
		HISTORICO,
		CAST(CASE WHEN CANCELADA = 1 AND VALOR_RAZAO > 0 THEN 'CANCELADO MAS TEM LANCAMENTO NA CONTABILIDADE' 
									WHEN VALOR_DOCUMENTO = VALOR_RAZAO THEN 'SEM ERRO'
							ELSE  
									'DIFERENCA ENTRE ESTOQUE E CONTABILIDADE'
							END 
						AS CHAR(254)) AS MOTIVO,
		OBSERVACAO,
		EMPRESA,
		DOCUMENTO_UKEY
	
		FROM ( SELECT
			'DEV NFS' AS OPERACAO,
			TMP_NFSDEV.NOTA AS DOCUMENTO,
			TMP_NFSDEV.VALORNOTA AS VALOR_DOCUMENTO,
			TMP_NFSDEV.EMISSAO,
			TMP_RAZAO.LANCAMENTO,
			--TMP_RAZAO.VALORLANCAMENTO AS VALOR_RAZAO,
			CAST((SELECT SUM(ISNULL(#TMP_RAZAO.VALORLANCAMENTO,0)) FROM #TMP_RAZAO WHERE B06_UKEYP = TMP_NFSDEV.UKEY) AS MONEY) AS VALOR_RAZAO,
			CAST(ISNULL(TMP_RAZAO.HISTORICO,'') AS VARCHAR(254)) AS HISTORICO,
			TMP_NFSDEV.CANCELADA AS CANCELADA,
			CAST(TMP_NFSDEV.OBS AS VARCHAR(254)) AS OBSERVACAO,
			TMP_NFSDEV.EMPRESA AS EMPRESA,
			TMP_NFSDEV.UKEY AS DOCUMENTO_UKEY
			FROM #TMP_NFSDEV AS TMP_NFSDEV
			JOIN #TMP_RAZAO AS TMP_RAZAO ON TMP_RAZAO.B06_UKEYP = TMP_NFSDEV.UKEY 
		)TMP

	--DELETO AS NOTAS QUE FORAM TRATADAS
	DELETE #TMP_NFSDEV WHERE UKEY IN (SELECT DOCUMENTO_UKEY FROM #TMP_RESULTADO)

	--DELETO OS LANÇAMENTOS QUE JÁ FORAM TRATADOS
	DELETE #TMP_RAZAO WHERE LANCAMENTO IN (SELECT LANCAMENTO FROM #TMP_RESULTADO)

	-- ARMAZENO AS DEMAIS NOTAS NO CURSOR DE RESULTADO
	INSERT INTO #TMP_RESULTADO 
	-- NF SEM TRATAMENTO
	SELECT 
			'DEV NFS' AS OPERACAO,
			TMP_NFSDEV.NOTA AS DOCUMENTO,
			TMP_NFSDEV.VALORNOTA AS VALOR_DOCUMENTO,
			TMP_NFSDEV.EMISSAO AS EMISSAO,
			'' AS LANCAMENTO,
			0 AS VALOR_RAZAO,
			'' AS HISTORICO,
			'NAO TEM LANCAMENTO NA CONTABILIDADE' AS MOTIVO,
			RTRIM(TMP_NFSDEV.OBS) +  CASE WHEN TMP_NFSDEV.CANCELADA = 1 THEN '-CANCELADA' ELSE '' END  AS OBSERVACAO,
			TMP_NFSDEV.EMPRESA AS EMPRESA,
			TMP_NFSDEV.UKEY AS DOCUMENTO_UKEY
	FROM #TMP_NFSDEV AS TMP_NFSDEV
	
	DROP TABLE #TMP_NFSDEV
	--================================================FINALIZADO O TRATAMENTO DAS DEVOLUÇÕES DE NOTAS DE SAÍDA===============================================================

	--================================================TRATANDO DOS LANÇAMENTOS CONTABEIS===============================================================
	-- ARMAZENO AS DEMAIS NOTAS NO CURSOR DE RESULTADO
	INSERT INTO #TMP_RESULTADO 
	-- NF SEM TRATAMENTO
	SELECT 
			'LC    ' AS OPERACAO,
			'' AS DOCUMENTO,
			0 AS VALOR_DOCUMENTO,
			TMP_RAZAO.DATALANCAMENTO  AS EMISSAO,
			TMP_RAZAO.lancamento AS LANCAMENTO,
			cast(TMP_RAZAO.valorlancamento as money) AS VALOR_RAZAO,
			ISNULL(TMP_RAZAO.HISTORICO,'') AS HISTORICO,
			CAST( 'LANCAMENTO SEM HISTORICO OU DE OPERACAO NAO TRATADA PELO RELATORIO' AS CHAR(254)) AS MOTIVO,
			CAST('LANCAMENTO' AS CHAR(254)) AS OBSERVACAO,
			CIA_001_C AS EMPRESA,
			TMP_RAZAO.B06_UKEY AS DOCUMENTO_UKEY
	FROM #TMP_RAZAO AS TMP_RAZAO
		JOIN STARWESTCON.DBO.CIA (NOLOCK) ON TMP_RAZAO.CIA_UKEY = CIA.UKEY

	DROP TABLE #TMP_RAZAO
	--================================================FINALIZADO O TRATAMENTO DOS LANÇAMENTOS CONTABEIS===============================================================

	SELECT DISTINCT * FROM #TMP_RESULTADO ORDER BY OPERACAO, DOCUMENTO
END